### ISSUE TITLE
Create groups for approvers and maintainers

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-builder#1]
Similar to what was decided for https://github.com/open-telemetry/opentelemetry-operator/issues/181, I'd like to have two groups of folks for this repository:

- approvers (@ open-telemetry/collector-approvers)
- maintainers (@jpkrohling, @ open-telemetry/collector-maintainers)

@open-telemetry/technical-committee, would one of you please create that?

**Comment by tigrannajaryan** [comment]
Done. I used existing collect-* teams, instead of creating new teams. We can change if in the future if needed.
