### ISSUE TITLE
Explicitly enable go modules

### ISSUE THREAD

**Issue by jiwen624** [open-telemetry/opentelemetry-collector-builder#11]
If for some reason go modules is not enabled, `go get` will report an error:

```
JYANG-MB at ~/go ❯ go get github.com/open-telemetry/opentelemetry-collector-builder
cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/local/Cellar/go/1.15.2/libexec/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/Users/yang/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
```
This is because `hashicorp/hcl` is currently V2 but `viper` depends on its V1 via Go modules (and `viper` is one of the dependencies of this repo). This will trigger the error above if (for some reason) Go modules is not enabled.

Therefore, I suggest to set the environment variable explicitly and run the command `GO111MODULE=on go get github.com/open-telemetry/opentelemetry-collector-builder` instead in the README.

**Comment by jpkrohling** [comment]
Would you mind sending a PR with the proposal?

**Comment by jiwen624** [comment]
@jpkrohling Please see the PR above. Thanks!
