### ISSUE TITLE
Backward compatibility issue

### ISSUE THREAD

**Issue by fangyi-zhou** [open-telemetry/opentelemetry-collector-builder#29]
In https://github.com/open-telemetry/opentelemetry-collector-builder/commit/c9fe6966eba55a28368caccb589b9c913adba7e5 , the template file `internal/scaffold/components.go` has been changed to use the the new API, and hence the builder does not work for earlier versions

**Comment by jpkrohling** [comment]
To be clear, you want to use the builder 0.22.0 to create a build based on a previous collector version? Would you mind if I ask why you'd want that?

**Comment by fangyi-zhou** [comment]
```
    otelcol_version: "0.23.0" # the OpenTelemetry Collector version to use as base for the distribution. Optional.
```
From this line in the example config file, I was under the impression that builder is independent of the version used for base. Hence I updated the builder to see if the #14 has been fixed, but it broke my build due to an API change in otelcol.

I didn't notice that the builder version scheme has been changed to match the otelcol version. If the maintainers think it's appropriate only to use builder vX.Y.Z to build collector using the same API version, i'd suggest remove the option to allow user to provide an otelcol version

**Comment by jpkrohling** [comment]
The versions have been aligned very recently, and the original idea is indeed to have the builder be able to build different versions of the collector. I was just genuinely curious about our use case :-)

The main problem right now is that the collector itself is moving very fast and breaking changes might happen. Once v1 is there, we should certainly be more careful and think of a strategy to build different versions. By then, the API on the collector side should be more stable.

**Comment by jpkrohling** [comment]
@fangyi-zhou should we close this one?
