### ISSUE TITLE
Verify whether the latest changes to the OpenTelemetry Collector require a change to the builder

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-builder#37]
There were a few changes to the OpenTelemetry Collector that seems like would affect the builder, such as:
https://github.com/open-telemetry/opentelemetry-collector/pull/3056

Before releasing 0.26.0, we need to make sure that those changes are accounted for.

**Comment by crearys** [comment]
This should have been fixed as part of issue:https://github.com/open-telemetry/opentelemetry-collector-builder/issues/38

**Comment by crearys** [comment]
@jpkrohling please can you do a release for 0.26.0

**Comment by jpkrohling** [comment]
Should be out in a few minutes.

**Comment by crearys** [comment]
Thanks!
