### ISSUE TITLE
Add badges for Code Coverage and CI status

### ISSUE THREAD

**Issue by xukaren** [open-telemetry/opentelemetry-collector-builder#44]
**Is your feature request related to a problem?**
Most of the existing OpenTelemetry repositories display a badge for CI status and possibly code coverage. In an effort to have the Collector Builder repository to be up to date and consistent with the other established SDKs and repositories, these badges should be included at the top of the main README.md file.

**Describe the solution you'd like.**
As a developer contributing to OpenTelemetry, I recommend adding a code coverage percentage and CI status badge at the top of the README document of the Collector Builder repo. These badges are a common feature of many modern open source projects, which improves readability and convenience to developers. By adding a badge to the README.md, with a quick scan, any observer will be able to know the status of the repository.

cc: @alolita

**Comment by jpkrohling** [comment]
Sure, go ahead.
