### ISSUE TITLE
Version & Date not updated by releaser

### ISSUE THREAD

**Issue by fangyi-zhou** [open-telemetry/opentelemetry-collector-builder#53]
https://github.com/open-telemetry/opentelemetry-collector-builder/blob/v0.28.0/cmd/root.go#L28

It remains dev for released versions, making the version command not very informative

**Comment by jpkrohling** [comment]
Is this a regression? I think it used to work before.

**Comment by fangyi-zhou** [comment]
I'm afraid that the version has been `dev` since the beginning of releases...

**Comment by fangyi-zhou** [comment]
Sorry I've been a bit unclear, I've installed the binary using `go get` and that seems to return version `dev` all the time. The released version seems fine.

**Comment by fangyi-zhou** [comment]
Feel free to close if that's the intended behaviour

**Comment by jpkrohling** [comment]
Thanks! That's indeed the intended behavior, as `go get` will download and compile locally, instead of using a released binary.
