### ISSUE TITLE
Admin rights for jpkrohling

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-builder#59]
I would like to request admin rights for this repository. My current need is to enable a set of checks, making them required before merging, such as the successful execution of e2e tests, and I cannot do that as a maintainer only.

cc @open-telemetry/collector-maintainers

**Comment by tigrannajaryan** [comment]
@jpkrohling you are an Admin now.

**Comment by jpkrohling** [comment]
Thanks!
