### ISSUE TITLE
Feature Request: Allow modules to be included based on golang build tags

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-builder#71]
For example, a `journaldlogreceiver` is being added to the contrib collector. This component will only have a meaningful implementation for Linux builds.

Without this feature, such components must rely on dummy implementations. In the case of `journaldreceiver`, such an implementation will simply return an error stating that the receiver is not available on non-Linux distributions.

**Comment by jpkrohling** [comment]
This would mean that you'll end up with the same distribution having different components based on the arch? Isn't that confusing to users reading the documentation for, say, "otelcol-contrib" and seeing references to `journaldreceiver`, but a cryptic runtime error when they use it on an unsupported platform? From an UX perspective, I would prefer if this receiver was included but would log a big warning if it's configured on a windows host.

**Comment by djaglowski** [comment]
> This would mean that you'll end up with the same distribution having different components based on the arch? 

Yes, and I think that this is the _effective_ result whether it is handled at the builder level or not. You make a great point about UX though. A dummy component would give the ability to provide a clearer error message. 

The notion of components that are limited to specific platforms is similar to current limitations based on signal type. If a user incorrectly assumes that X processor is useful for metrics, they'll eventually learn otherwise, whether by documentation or error message.

Thanks for considering. I didn't want to make any assumptions about the preferred approach. Your point about controlling the error message gives us a clearer direction.
